# Generated by Django 5.0 on 2023-12-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author_post_content_post_date_posted_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stripped_content',
            field=models.TextField(default='.'),
        ),
    ]
